// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package ubl.cec


/** 
        A container for all extensions present in the document.
      
*/
case class UBLExtensionsType(UBLExtension: ubl.cec.UBLExtensionType*)


/** 
        A single extension for private use.
      
*/
case class UBLExtensionType(ID: Option[ubl.cbc.IDType] = None,
  Name: Option[ubl.cbc.NameType] = None,
  ExtensionAgencyID: Option[ubl.cec.ExtensionAgencyIDType] = None,
  ExtensionAgencyName: Option[ubl.cec.ExtensionAgencyNameType] = None,
  ExtensionVersionID: Option[ubl.cec.ExtensionVersionIDType] = None,
  ExtensionAgencyURI: Option[ubl.cec.ExtensionAgencyURIType] = None,
  ExtensionURI: Option[ubl.cec.ExtensionURIType] = None,
  ExtensionReasonCode: Option[ubl.cec.ExtensionReasonCodeType] = None,
  ExtensionReason: Option[ubl.cec.ExtensionReasonType] = None,
  ExtensionContent: ubl.cec.ExtensionContentType)


case class ExtensionAgencyIDType(value: String,
  schemeID: Option[String] = None,
  schemeName: Option[String] = None,
  schemeAgencyID: Option[String] = None,
  schemeAgencyName: Option[String] = None,
  schemeVersionID: Option[String] = None,
  schemeDataURI: Option[java.net.URI] = None,
  schemeURI: Option[java.net.URI] = None) extends ubl.udt.IdentifierTypable


case class ExtensionAgencyNameType(value: String,
  languageID: Option[String] = None,
  languageLocaleID: Option[String] = None) extends ubl.udt.TextTypable


case class ExtensionAgencyURIType(value: String,
  schemeID: Option[String] = None,
  schemeName: Option[String] = None,
  schemeAgencyID: Option[String] = None,
  schemeAgencyName: Option[String] = None,
  schemeVersionID: Option[String] = None,
  schemeDataURI: Option[java.net.URI] = None,
  schemeURI: Option[java.net.URI] = None) extends ubl.udt.IdentifierTypable


case class ExtensionReasonType(value: String,
  languageID: Option[String] = None,
  languageLocaleID: Option[String] = None) extends ubl.udt.TextTypable


case class ExtensionReasonCodeType(value: String,
  listID: Option[String] = None,
  listAgencyID: Option[String] = None,
  listAgencyName: Option[String] = None,
  listName: Option[String] = None,
  listVersionID: Option[String] = None,
  name: Option[String] = None,
  languageID: Option[String] = None,
  listURI: Option[java.net.URI] = None,
  listSchemeURI: Option[java.net.URI] = None) extends ubl.udt.CodeTypable


case class ExtensionURIType(value: String,
  schemeID: Option[String] = None,
  schemeName: Option[String] = None,
  schemeAgencyID: Option[String] = None,
  schemeAgencyName: Option[String] = None,
  schemeVersionID: Option[String] = None,
  schemeDataURI: Option[java.net.URI] = None,
  schemeURI: Option[java.net.URI] = None) extends ubl.udt.IdentifierTypable


case class ExtensionVersionIDType(value: String,
  schemeID: Option[String] = None,
  schemeName: Option[String] = None,
  schemeAgencyID: Option[String] = None,
  schemeAgencyName: Option[String] = None,
  schemeVersionID: Option[String] = None,
  schemeDataURI: Option[java.net.URI] = None,
  schemeURI: Option[java.net.URI] = None) extends ubl.udt.IdentifierTypable

