// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package ubl.cec


case class ExtensionContentType(extensioncontenttypeoption: Option[scalaxb.DataRecord[Any]] = None)

trait ExtensionContentTypeOption
