// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package ubl.ar


/** 
            <ccts:Component xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
               <ccts:ComponentType>ABIE</ccts:ComponentType>
               <ccts:DictionaryEntryName>Application Response. Details</ccts:DictionaryEntryName>
               <ccts:Definition>A document to indicate the application s response to a transaction. This may be a business response and/or a technical response, sent automatically by an application or initiated by a user.</ccts:Definition>
               <ccts:ObjectClass>Application Response</ccts:ObjectClass>
            </ccts:Component>
         
*/
case class ApplicationResponseType(UBLExtensions: Option[ubl.cec.UBLExtensionsType] = None,
  UBLVersionID: Option[ubl.cbc.UBLVersionIDType] = None,
  CustomizationID: Option[ubl.cbc.CustomizationIDType] = None,
  ProfileID: Option[ubl.cbc.ProfileIDType] = None,
  ProfileExecutionID: Option[ubl.cbc.ProfileExecutionIDType] = None,
  ID: ubl.cbc.IDType,
  UUID: Option[ubl.cbc.UUIDType] = None,
  IssueDate: ubl.cbc.IssueDateType,
  IssueTime: Option[ubl.cbc.IssueTimeType] = None,
  ResponseDate: Option[ubl.cbc.ResponseDateType] = None,
  ResponseTime: Option[ubl.cbc.ResponseTimeType] = None,
  Note: Seq[ubl.cbc.NoteType] = Nil,
  VersionID: Option[ubl.cbc.VersionIDType] = None,
  Signature: Seq[ubl.cac.SignatureType] = Nil,
  SenderParty: ubl.cac.PartyType,
  ReceiverParty: ubl.cac.PartyType,
  DocumentResponse: Seq[ubl.cac.DocumentResponseType] = Nil)

