// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package ubl.sac


/** 
         <ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsd="http://www.w3.org/2001/XMLSchema">This class captures a single signature and optionally associates to a signature in the document with the corresponding identifier.</ccts:Definition>
       
*/
case class SignatureInformationType(ID: Option[ubl.cbc.IDType] = None,
  ReferencedSignatureID: Option[ubl.sbc.ReferencedSignatureIDType] = None,
  Signature: Option[org.w3c.xmldsig.SignatureType] = None)

