// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package un.ccts


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000001</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Amount. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A number of monetary units specified in a currency where the unit of the currency is explicit or implied.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Amount</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">decimal</ccts:PrimitiveType>
         
*/
trait AmountTypable {
  val value: BigDecimal
  val currencyID: Option[String]
  val currencyCodeListVersionID: Option[String]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000001</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Amount. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A number of monetary units specified in a currency where the unit of the currency is explicit or implied.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Amount</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">decimal</ccts:PrimitiveType>
         
*/
case class AmountType(value: BigDecimal,
  currencyID: Option[String] = None,
  currencyCodeListVersionID: Option[String] = None) extends AmountTypable


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000002</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Binary Object. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A set of finite-length sequences of binary octets.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Binary Object</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">binary</ccts:PrimitiveType>
         
*/
trait BinaryObjectTypable {
  val value: scalaxb.Base64Binary
  val format: Option[String]
  val mimeCode: Option[String]
  val encodingCode: Option[String]
  val characterSetCode: Option[String]
  val uri: Option[java.net.URI]
  val filename: Option[String]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000002</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Binary Object. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A set of finite-length sequences of binary octets.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Binary Object</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">binary</ccts:PrimitiveType>
         
*/
case class BinaryObjectType(value: scalaxb.Base64Binary,
  format: Option[String] = None,
  mimeCode: Option[String] = None,
  encodingCode: Option[String] = None,
  characterSetCode: Option[String] = None,
  uri: Option[java.net.URI] = None,
  filename: Option[String] = None) extends BinaryObjectTypable


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000007</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Code. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A character string (letters, figures, or symbols) that for brevity and/or languange independence may be used to represent or replace a definitive value or text of an attribute together with relevant supplementary information.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Code</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
            <ccts:UsageRule xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Should not be used if the character string identifies an instance of an object class or an object in the real world, in which case the Identifier. Type should be used.</ccts:UsageRule>
         
*/
trait CodeTypable {
  val value: String
  val listID: Option[String]
  val listAgencyID: Option[String]
  val listAgencyName: Option[String]
  val listName: Option[String]
  val listVersionID: Option[String]
  val name: Option[String]
  val languageID: Option[String]
  val listURI: Option[java.net.URI]
  val listSchemeURI: Option[java.net.URI]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000007</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Code. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A character string (letters, figures, or symbols) that for brevity and/or languange independence may be used to represent or replace a definitive value or text of an attribute together with relevant supplementary information.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Code</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
            <ccts:UsageRule xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Should not be used if the character string identifies an instance of an object class or an object in the real world, in which case the Identifier. Type should be used.</ccts:UsageRule>
         
*/
case class CodeType(value: String,
  listID: Option[String] = None,
  listAgencyID: Option[String] = None,
  listAgencyName: Option[String] = None,
  listName: Option[String] = None,
  listVersionID: Option[String] = None,
  name: Option[String] = None,
  languageID: Option[String] = None,
  listURI: Option[java.net.URI] = None,
  listSchemeURI: Option[java.net.URI] = None) extends CodeTypable


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000008</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Date Time. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A particular point in the progression of time together with the relevant supplementary information.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Date Time</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
            <ccts:UsageRule xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Can be used for a date and/or time.</ccts:UsageRule>
         
*/
case class DateTimeType(value: String,
  format: Option[String] = None)


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000011</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Identifier. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A character string to identify and distinguish uniquely, one instance of an object in an identification scheme from all other objects in the same scheme together with relevant supplementary information.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Identifier</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
         
*/
trait IdentifierTypable {
  val value: String
  val schemeID: Option[String]
  val schemeName: Option[String]
  val schemeAgencyID: Option[String]
  val schemeAgencyName: Option[String]
  val schemeVersionID: Option[String]
  val schemeDataURI: Option[java.net.URI]
  val schemeURI: Option[java.net.URI]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000011</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Identifier. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A character string to identify and distinguish uniquely, one instance of an object in an identification scheme from all other objects in the same scheme together with relevant supplementary information.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Identifier</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
         
*/
case class IdentifierType(value: String,
  schemeID: Option[String] = None,
  schemeName: Option[String] = None,
  schemeAgencyID: Option[String] = None,
  schemeAgencyName: Option[String] = None,
  schemeVersionID: Option[String] = None,
  schemeDataURI: Option[java.net.URI] = None,
  schemeURI: Option[java.net.URI] = None) extends IdentifierTypable


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000012</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Indicator. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A list of two mutually exclusive Boolean values that express the only possible states of a Property.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Indicator</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
         
*/
case class IndicatorType(value: String,
  format: Option[String] = None)


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000013</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Measure. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A numeric value determined by measuring an object along with the specified unit of measure.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Measure</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">decimal</ccts:PrimitiveType>
         
*/
trait MeasureTypable {
  val value: BigDecimal
  val unitCode: Option[String]
  val unitCodeListVersionID: Option[String]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000013</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Measure. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A numeric value determined by measuring an object along with the specified unit of measure.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Measure</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">decimal</ccts:PrimitiveType>
         
*/
case class MeasureType(value: BigDecimal,
  unitCode: Option[String] = None,
  unitCodeListVersionID: Option[String] = None) extends MeasureTypable


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000014</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Numeric. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Numeric information that is assigned or is determined by calculation, counting, or sequencing. It does not require a unit of quantity or unit of measure.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Numeric</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
         
*/
trait NumericTypable {
  val value: BigDecimal
  val format: Option[String]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000014</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Numeric. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Numeric information that is assigned or is determined by calculation, counting, or sequencing. It does not require a unit of quantity or unit of measure.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Numeric</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
         
*/
case class NumericType(value: BigDecimal,
  format: Option[String] = None) extends NumericTypable


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000018</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Quantity. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A counted number of non-monetary units possibly including fractions.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Quantity</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">decimal</ccts:PrimitiveType>
         
*/
trait QuantityTypable {
  val value: BigDecimal
  val unitCode: Option[String]
  val unitCodeListID: Option[String]
  val unitCodeListAgencyID: Option[String]
  val unitCodeListAgencyName: Option[String]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000018</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Quantity. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A counted number of non-monetary units possibly including fractions.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Quantity</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">decimal</ccts:PrimitiveType>
         
*/
case class QuantityType(value: BigDecimal,
  unitCode: Option[String] = None,
  unitCodeListID: Option[String] = None,
  unitCodeListAgencyID: Option[String] = None,
  unitCodeListAgencyName: Option[String] = None) extends QuantityTypable


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000019</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Text. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A character string (i.e. a finite set of characters) generally in the form of words of a language.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Text</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
         
*/
trait TextTypable {
  val value: String
  val languageID: Option[String]
  val languageLocaleID: Option[String]
}


/** 
            <ccts:UniqueID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">UNDT000019</ccts:UniqueID>
            <ccts:CategoryCode xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">CCT</ccts:CategoryCode>
            <ccts:DictionaryEntryName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Text. Type</ccts:DictionaryEntryName>
            <ccts:VersionID xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">1.0</ccts:VersionID>
            <ccts:Definition xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">A character string (i.e. a finite set of characters) generally in the form of words of a language.</ccts:Definition>
            <ccts:RepresentationTermName xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">Text</ccts:RepresentationTermName>
            <ccts:PrimitiveType xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:ccts="urn:un:unece:uncefact:documentation:2">string</ccts:PrimitiveType>
         
*/
case class TextType(value: String,
  languageID: Option[String] = None,
  languageLocaleID: Option[String] = None) extends TextTypable

