// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package ubl.oc


/** 
            <ccts:Component xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:OrderChange-2" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
               <ccts:ComponentType>ABIE</ccts:ComponentType>
               <ccts:DictionaryEntryName>Order Change. Details</ccts:DictionaryEntryName>
               <ccts:Definition>The document used to specify changes to an existing Order.</ccts:Definition>
               <ccts:ObjectClass>Order Change</ccts:ObjectClass>
               <ccts:AlternativeBusinessTerms>Purchase Order Change</ccts:AlternativeBusinessTerms>
            </ccts:Component>
         
*/
case class OrderChangeType(orderchangetypesequence1: ubl.oc.OrderChangeTypeSequence1,
  orderchangetypesequence2: ubl.oc.OrderChangeTypeSequence2,
  orderchangetypesequence3: ubl.oc.OrderChangeTypeSequence3,
  orderchangetypesequence4: ubl.oc.OrderChangeTypeSequence4,
  orderchangetypesequence5: ubl.oc.OrderChangeTypeSequence5) {
  lazy val UBLExtensions = orderchangetypesequence1.UBLExtensions
  lazy val UBLVersionID = orderchangetypesequence1.UBLVersionID
  lazy val CustomizationID = orderchangetypesequence1.CustomizationID
  lazy val ProfileID = orderchangetypesequence1.ProfileID
  lazy val ProfileExecutionID = orderchangetypesequence1.ProfileExecutionID
  lazy val ID = orderchangetypesequence1.ID
  lazy val SalesOrderID = orderchangetypesequence1.SalesOrderID
  lazy val CopyIndicator = orderchangetypesequence1.CopyIndicator
  lazy val UUID = orderchangetypesequence1.UUID
  lazy val IssueDate = orderchangetypesequence1.IssueDate
  lazy val IssueTime = orderchangetypesequence2.IssueTime
  lazy val SequenceNumberID = orderchangetypesequence2.SequenceNumberID
  lazy val Note = orderchangetypesequence2.Note
  lazy val RequestedInvoiceCurrencyCode = orderchangetypesequence2.RequestedInvoiceCurrencyCode
  lazy val DocumentCurrencyCode = orderchangetypesequence2.DocumentCurrencyCode
  lazy val PricingCurrencyCode = orderchangetypesequence2.PricingCurrencyCode
  lazy val TaxCurrencyCode = orderchangetypesequence2.TaxCurrencyCode
  lazy val CustomerReference = orderchangetypesequence2.CustomerReference
  lazy val AccountingCostCode = orderchangetypesequence2.AccountingCostCode
  lazy val AccountingCost = orderchangetypesequence2.AccountingCost
  lazy val LineCountNumeric = orderchangetypesequence3.LineCountNumeric
  lazy val ValidityPeriod = orderchangetypesequence3.ValidityPeriod
  lazy val OrderReference = orderchangetypesequence3.OrderReference
  lazy val QuotationDocumentReference = orderchangetypesequence3.QuotationDocumentReference
  lazy val OriginatorDocumentReference = orderchangetypesequence3.OriginatorDocumentReference
  lazy val AdditionalDocumentReference = orderchangetypesequence3.AdditionalDocumentReference
  lazy val Contract = orderchangetypesequence3.Contract
  lazy val Signature = orderchangetypesequence3.Signature
  lazy val BuyerCustomerParty = orderchangetypesequence3.BuyerCustomerParty
  lazy val SellerSupplierParty = orderchangetypesequence3.SellerSupplierParty
  lazy val OriginatorCustomerParty = orderchangetypesequence4.OriginatorCustomerParty
  lazy val FreightForwarderParty = orderchangetypesequence4.FreightForwarderParty
  lazy val AccountingCustomerParty = orderchangetypesequence4.AccountingCustomerParty
  lazy val AccountingSupplierParty = orderchangetypesequence4.AccountingSupplierParty
  lazy val Delivery = orderchangetypesequence4.Delivery
  lazy val DeliveryTerms = orderchangetypesequence4.DeliveryTerms
  lazy val PaymentMeans = orderchangetypesequence4.PaymentMeans
  lazy val PaymentTerms = orderchangetypesequence4.PaymentTerms
  lazy val TransactionConditions = orderchangetypesequence4.TransactionConditions
  lazy val AllowanceCharge = orderchangetypesequence4.AllowanceCharge
  lazy val TaxExchangeRate = orderchangetypesequence5.TaxExchangeRate
  lazy val PricingExchangeRate = orderchangetypesequence5.PricingExchangeRate
  lazy val PaymentExchangeRate = orderchangetypesequence5.PaymentExchangeRate
  lazy val DestinationCountry = orderchangetypesequence5.DestinationCountry
  lazy val TaxTotal = orderchangetypesequence5.TaxTotal
  lazy val AnticipatedMonetaryTotal = orderchangetypesequence5.AnticipatedMonetaryTotal
  lazy val OrderLine = orderchangetypesequence5.OrderLine
}


case class OrderChangeTypeSequence1(UBLExtensions: Option[ubl.cec.UBLExtensionsType] = None,
  UBLVersionID: Option[ubl.cbc.UBLVersionIDType] = None,
  CustomizationID: Option[ubl.cbc.CustomizationIDType] = None,
  ProfileID: Option[ubl.cbc.ProfileIDType] = None,
  ProfileExecutionID: Option[ubl.cbc.ProfileExecutionIDType] = None,
  ID: Option[ubl.cbc.IDType] = None,
  SalesOrderID: Option[ubl.cbc.SalesOrderIDType] = None,
  CopyIndicator: Option[ubl.cbc.CopyIndicatorType] = None,
  UUID: Option[ubl.cbc.UUIDType] = None,
  IssueDate: ubl.cbc.IssueDateType)

case class OrderChangeTypeSequence2(IssueTime: Option[ubl.cbc.IssueTimeType] = None,
  SequenceNumberID: ubl.cbc.SequenceNumberIDType,
  Note: Seq[ubl.cbc.NoteType] = Nil,
  RequestedInvoiceCurrencyCode: Option[ubl.cbc.RequestedInvoiceCurrencyCodeType] = None,
  DocumentCurrencyCode: Option[ubl.cbc.DocumentCurrencyCodeType] = None,
  PricingCurrencyCode: Option[ubl.cbc.PricingCurrencyCodeType] = None,
  TaxCurrencyCode: Option[ubl.cbc.TaxCurrencyCodeType] = None,
  CustomerReference: Option[ubl.cbc.CustomerReferenceType] = None,
  AccountingCostCode: Option[ubl.cbc.AccountingCostCodeType] = None,
  AccountingCost: Option[ubl.cbc.AccountingCostType] = None)

case class OrderChangeTypeSequence3(LineCountNumeric: Option[ubl.cbc.LineCountNumericType] = None,
  ValidityPeriod: Seq[ubl.cac.PeriodType] = Nil,
  OrderReference: ubl.cac.OrderReferenceType,
  QuotationDocumentReference: Option[ubl.cac.DocumentReferenceType] = None,
  OriginatorDocumentReference: Option[ubl.cac.DocumentReferenceType] = None,
  AdditionalDocumentReference: Seq[ubl.cac.DocumentReferenceType] = Nil,
  Contract: Seq[ubl.cac.ContractType] = Nil,
  Signature: Seq[ubl.cac.SignatureType] = Nil,
  BuyerCustomerParty: ubl.cac.CustomerPartyType,
  SellerSupplierParty: ubl.cac.SupplierPartyType)

case class OrderChangeTypeSequence4(OriginatorCustomerParty: Option[ubl.cac.CustomerPartyType] = None,
  FreightForwarderParty: Option[ubl.cac.PartyType] = None,
  AccountingCustomerParty: Option[ubl.cac.CustomerPartyType] = None,
  AccountingSupplierParty: Option[ubl.cac.SupplierPartyType] = None,
  Delivery: Seq[ubl.cac.DeliveryType] = Nil,
  DeliveryTerms: Option[ubl.cac.DeliveryTermsType] = None,
  PaymentMeans: Seq[ubl.cac.PaymentMeansType] = Nil,
  PaymentTerms: Seq[ubl.cac.PaymentTermsType] = Nil,
  TransactionConditions: Option[ubl.cac.TransactionConditionsType] = None,
  AllowanceCharge: Seq[ubl.cac.AllowanceChargeType] = Nil)

case class OrderChangeTypeSequence5(TaxExchangeRate: Option[ubl.cac.ExchangeRateType] = None,
  PricingExchangeRate: Option[ubl.cac.ExchangeRateType] = None,
  PaymentExchangeRate: Option[ubl.cac.ExchangeRateType] = None,
  DestinationCountry: Option[ubl.cac.CountryType] = None,
  TaxTotal: Seq[ubl.cac.TaxTotalType] = Nil,
  AnticipatedMonetaryTotal: Option[ubl.cac.MonetaryTotalType] = None,
  OrderLine: Seq[ubl.cac.OrderLineType] = Nil)

