// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package ubl.sbc


case class ReferencedSignatureIDType(value: String,
  schemeID: Option[String] = None,
  schemeName: Option[String] = None,
  schemeAgencyID: Option[String] = None,
  schemeAgencyName: Option[String] = None,
  schemeVersionID: Option[String] = None,
  schemeDataURI: Option[java.net.URI] = None,
  schemeURI: Option[java.net.URI] = None) extends ubl.udt.IdentifierTypable

